export const MEDICAL_SPECIALTIES = [
  "Anatomía Patológica",
  "Anestesiología",
  "Cardiología",
  "Cirugía Bariátrica",
  "Cirugía Cardiovascular",
  "Cirugía de Mano",
  "Cirugía de Tórax",
  "Cirugía General",
  "Cirugía Maxilofacial",
  "Cirugía Pediátrica",
  "Cirugía Plástica",
  "Coloproctología",
  "Dermatología",
  "Dermatología Pediátrica",
  "Ecografía General",
  "Electrofisiología y Arritmias",
  "Endocrinología",
  "Endocrinología Pediátrica",
  "Fisiatría",
  "Gastroenterología",
  "Gastroenterología Pediátrica",
  "Ginecología",
  "Hematología",
  "Hematología Pediátrica",
  "Hemodinamia",
  "Imagenología",
  "Infectología",
  "Intensivista",
  "Mastología",
  "Medicina Física y Rehabilitación",
  "Medicina Interna",
  "Medicina Perinatal",
  "Nefrología",
  "Neonatología",
  "Neumonología",
  "Neumonología Pediátrica",
  "Neurocirugía",
  "Neurología",
  "Obstetricia",
  "Odontología Pediátrica",
  "Odontología y Endodoncia",
  "Oftalmología",
  "Oncología",
  "Ortopedia y Traumatología",
  "Otorrinolaringología",
  "Pediatría",
  "Psicología Clínica",
  "Reumatología",
  "Terapia Intensiva",
  "Traumatología",
  "Urología",
  "Urología Pediátrica",
] as const;
