import type { WizardForm, QuickPatientForm } from "./wizard-types";

export const EMPTY_FORM: WizardForm = {
  entryMode: "consulta",
  patientId: "",
  linkedRecordId: "",
  specialtyKind: "medicina-general",
  patientStatus: "activo",
  appointmentId: null,
  gender: "",
  occupation: "",
  insurance: "",
  blood_type: "",
  emergency_contact: { name: "", relationship: "", phone: "" },
  consultationType: "primera-vez",
  informantSource: "paciente",
  informantReliability: "confiable",
  referringDoctor: "",
  chiefComplaint: "",
  anamnesis: "",
  symptoms: "",
  medicalHistory: "",
  backgrounds: {
    pathological: "",
    surgical: "",
    allergic: "",
    pharmacological: "",
    family: "",
    toxic: "",
    gynecoObstetric: "",
  },
  reviewOfSystems: {
    cardiovascular: { present: false, notes: "" },
    respiratory: { present: false, notes: "" },
    gastrointestinal: { present: false, notes: "" },
    genitourinary: { present: false, notes: "" },
    neurological: { present: false, notes: "" },
    musculoskeletal: { present: false, notes: "" },
    dermatological: { present: false, notes: "" },
    endocrine: { present: false, notes: "" },
    psychiatric: { present: false, notes: "" },
    hematological: { present: false, notes: "" },
  },
  vitalSigns: {
    bloodPressure: "",
    heartRate: "",
    respiratoryRate: "",
    temperature: "",
    oxygenSaturation: "",
    weight: "",
    height: "",
    mean_arterial_pressure: "",
  },
  physicalExam: [],
  generalCondition: "",
  painScale: null,
  diagnosis: "",
  cieCodes: "",
  clinicalAnalysis: "",
  medical_orders: { diet_type: "", general_measures: "", nursing_cares: "" },
  treatmentTemplateId: "",
  treatmentPlan: "",
  medicationInstructions: "",
  recommendations: "",
  warningSigns: "",
  labOrders: [],
  imagingOrders: [],
  medicalReferral: null,
  currentMedications: [],
  medicationInstructionsStructured: [],
  evolutionStatus: "",
  nextFollowUpDate: "",
  soapSubjective: "",
  soapObjective: "",
  soapAssessment: "",
  soapPlan: "",
  prognosisVital: "",
  prognosisFunctional: "",
  pediatricData: {
    headCircumference: "",
    developmentStage: "",
    vaccineStatus: "",
  },
};

export const EMPTY_QUICK_PATIENT: QuickPatientForm = {
  documentNumber: "",
  firstName: "",
  lastName: "",
  phone: "",
  birthDate: "",
};
